-- Player IDs are generated by the server; retain existing IDs but remove the
-- editable playing-position field.
ALTER TABLE "players" DROP COLUMN IF EXISTS "position";

-- Categories and disciplines are option-backed freeform values. Existing enum
-- values are preserved as text while new values can be entered by admins.
ALTER TABLE "players" ALTER COLUMN "category" TYPE varchar(100) USING "category"::text;
ALTER TABLE "matches" ALTER COLUMN "discipline" TYPE varchar(100) USING "discipline"::text;
ALTER TABLE "matches" ALTER COLUMN "category" TYPE varchar(100) USING "category"::text;
ALTER TABLE "match_points" ALTER COLUMN "discipline" TYPE varchar(100) USING "discipline"::text;
ALTER TABLE "match_points" ALTER COLUMN "category" TYPE varchar(100) USING "category"::text;
ALTER TABLE "match_registrations" ALTER COLUMN "category" TYPE varchar(100) USING "category"::text;

ALTER TABLE "site_content" ADD COLUMN IF NOT EXISTS "contact_email" varchar(255) DEFAULT '' NOT NULL;
ALTER TABLE "site_content" ADD COLUMN IF NOT EXISTS "contact_phone" varchar(30) DEFAULT '' NOT NULL;
ALTER TABLE "site_content" ADD COLUMN IF NOT EXISTS "facebook_url" text DEFAULT '' NOT NULL;
ALTER TABLE "site_content" ADD COLUMN IF NOT EXISTS "youtube_url" text DEFAULT '' NOT NULL;

CREATE TABLE IF NOT EXISTS "password_reset_tokens" (
  "id" serial PRIMARY KEY NOT NULL,
  "user_id" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "token_hash" varchar(128) NOT NULL UNIQUE,
  "expires_at" timestamp NOT NULL,
  "created_at" timestamp DEFAULT now() NOT NULL
);
